title: Bolans jekyll theme
author: Kodymer
email: keymer.leon@kodymer.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Bolans date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
bolans:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: bolans
    # github:  bolans
    # rss: rss
    # dribbble: bolans
    facebook: bolans
    # flickr:   bolans
    instagram: bolans
    linkedin: bolans
    # pinterest: bolans
    # youtube: bolans
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: bolans
    # googleplus: +bolans
    # microdotblog: bolans
    # keybase: bolans

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: bolans

# If you want to apply a specific style in your site, uncomment
# this and add the style to the site as should show up
# default style is style1
#style: style1 #[style2, style3, style4]

plugins:
 - jekyll-feed
 - jekyll-seo-tag

collections:
  services:
    output: true
